# Generated by Django 3.1.3 on 2020-11-04 13:33

from django.db import migrations, models
import rater.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to=rater.models.upload_path)),
            ],
        ),
    ]
